// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: report_baseline.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getReportJobByID = `-- name: GetReportJobByID :one
SELECT
    id,
    request_id,
    source,
    job_type,
    target_type,
    target_id,
    asynq_task_id,
    queue_name,
    report_id,
    template_id,
    status,
    error_code,
    error_message,
    retry_count,
    max_attempts,
    started_at,
    finished_at,
    created_at
FROM report_jobs
WHERE id = $1
`

type GetReportJobByIDRow struct {
	ID           pgtype.UUID        `json:"id"`
	RequestID    pgtype.Text        `json:"request_id"`
	Source       string             `json:"source"`
	JobType      string             `json:"job_type"`
	TargetType   string             `json:"target_type"`
	TargetID     string             `json:"target_id"`
	AsynqTaskID  pgtype.Text        `json:"asynq_task_id"`
	QueueName    string             `json:"queue_name"`
	ReportID     pgtype.UUID        `json:"report_id"`
	TemplateID   pgtype.UUID        `json:"template_id"`
	Status       string             `json:"status"`
	ErrorCode    pgtype.Text        `json:"error_code"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	RetryCount   int32              `json:"retry_count"`
	MaxAttempts  int32              `json:"max_attempts"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetReportJobByID(ctx context.Context, id pgtype.UUID) (GetReportJobByIDRow, error) {
	row := q.db.QueryRow(ctx, getReportJobByID, id)
	var i GetReportJobByIDRow
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.Source,
		&i.JobType,
		&i.TargetType,
		&i.TargetID,
		&i.AsynqTaskID,
		&i.QueueName,
		&i.ReportID,
		&i.TemplateID,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.RetryCount,
		&i.MaxAttempts,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}
